name: Build and Push Docker Image

on:
  schedule:
    # Tự động chạy hàng ngày vào 0h
    - cron: "0 0 * * *"
  workflow_dispatch: # Cho phép chạy thủ công nếu cần

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build và push image đa nền tảng
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bibica/lcmp-auto-wordpress-wp-cli-php8.3-fpm-alpine:latest
          platforms: linux/amd64,linux/arm64
